apiVersion: v1
kind: Service
metadata:
  name: earningsiq-api
  namespace: earningsiq
spec:
  type: NodePort
  selector:
    app: earningsiq-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
