apiVersion: v1
kind: ConfigMap
metadata:
  name: earningsiq-config
  namespace: earningsiq
data:
  PROJECT_NAME: EarningsIQ
  ENVIRONMENT: kubernetes
  LLM_PROVIDER: ollama
  GROQ_MODEL: llama3-8b-8192
  OLLAMA_BASE_URL: http://ollama.default.svc.cluster.local:11434
  OLLAMA_MODEL: llama3
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: earningsiq
  POSTGRES_USER: earningsiq
  DATABASE_URL: postgresql://earningsiq:earningsiq@postgres:5432/earningsiq
  REDIS_URL: redis://redis:6379/0
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SEC_USER_AGENT: Saif Mohammed smohammed8@seattleu.edu
  API_BASE_URL: http://earningsiq-api:8000
